# Generated by Django 3.2.9 on 2023-02-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacklink',
            name='description',
            field=models.TextField(default=1, verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='feedbacklink',
            table='feedback',
        ),
    ]
