# Generated by Django 3.2.9 on 2023-02-13 14:16

import company.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loga', models.ImageField(blank=True, null=True, upload_to=company.services.get_upload_path, validators=[company.services.validate_file_extension], verbose_name='')),
                ('description', models.TextField(verbose_name='Опишите нашего партнёра')),
            ],
            options={
                'verbose_name': 'Добавить партнеров',
                'verbose_name_plural': 'Наши партнеры',
                'db_table': 'partners',
            },
        ),
        migrations.AlterModelOptions(
            name='createstaff',
            options={'verbose_name': 'Специалиста', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
